### PR TITLE
Enabled fetch pending transactions for Hyperledger Besu client

### PR DESCRIPTION
**Pull request by MASDXI**
## Motivation

In the blockscout backend implementing method `txpool_besuTransactions` does not include details of the transaction details and requires an additional RPC call `eth_getTransactionByHash` to retrieve details of each transaction.  
Now Hyperledger Besu has a method for querying pending transactions from mempool via `txpool_besuPendingTransactions` [[1]](https://besu.hyperledger.org/public-networks/reference/api#txpool_besupendingtransactions_)  similar to `parity_pendingTransactions` but requires `numResults` parameter to limit maximum transactions to return. 
In this Pull request parameter, the value will be set to `512` which is the default value of the bonsai data structure[[2]](https://besu.hyperledger.org/public-networks/reference/cli/options#bonsai-historical-block-limit)
to handle pending transactions[[3]](https://etherscan.io/chart/pendingtx) on the Ethereum mainnet requires more than `50000`.

blockscout_pending_tx_besu

The issue that related to this PR
[#2858](https://github.com/blockscout/blockscout/issues/2858) Logic for pending transaction hyperledger besu
[#3117](https://github.com/blockscout/blockscout/issues/3117) error on pending tx in besu

_Reference:_
_[1] https://besu.hyperledger.org/public-networks/reference/api#txpool_besupendingtransactions_
_[2] https://besu.hyperledger.org/public-networks/reference/cli/options#bonsai-historical-block-limit_
_[3] https://etherscan.io/chart/pendingtx_

### Enhancements
Re-enabled fetch pending transactions for Hyperledger Besu client. 

### Bug Fixes

- Change `TXPOOL` method for Hyperledger Besu Client from `txpool_besuTransactions` to `txpool_besuPendingTransactions`.
- Adding fixed integer value limit return to `512` for `txpool_besuPendingTransactions`
- Remove condition to check if  `ETHEREUM_JSONRPC_VARIANT ` is besu will disable fetch pending transaction.

### Incompatible Changes

none.

## Upgrading

none.

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by vbaranov — APPROVED** [review]
Thanks for the contribution!

**Comment by iampkuhz** [comment]
does anyone turn on besu pending transaction monitoring?

We are faced with this problem and failed to get pending transaction from besu.

the error log in besu:

```
2024-08-05 21:06:50.156+08:00 | vert.x-worker-thread-10 | TRACE | AbstractJsonRpcExecutor | {"id":1,"params":[],"method":"txpool_besuPendingTransactions","jsonrpc":"2.0"}
2024-08-05 21:06:50.156+08:00 | vert.x-worker-thread-10 | DEBUG | JsonRpcExecutor | JSON-RPC request -> txpool_besuPendingTransactions []
2024-08-05 21:06:50.157+08:00 | vert.x-worker-thread-10 | DEBUG | BaseJsonRpcProcessor | Invalid Params for method: txpool_besuPendingTransactions org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcParameters: Missing required json rpc parameter at index 0
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.lambda$required$0(JsonRpcParameter.java:47)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.required(JsonRpcParameter.java:45)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.JsonRpcRequest.getRequiredParameter(JsonRpcRequest.java:134)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.JsonRpcRequestContext.getRequiredParameter(JsonRpcRequestContext.java:65)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TxPoolBesuPendingTransactions.response(TxPoolBesuPendingTransactions.java:52)
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44)
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
        at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)
        at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87)
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57)
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
        at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

2024-08-05 21:06:50.157+08:00 | vert.x-worker-thread-10 | TRACE | AbstractJsonRpcExecutor | {"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid params"}}
```

it seems that the default `numResults` value `512` is not passed to the request
```ex
           %{id: 1, method: "txpool_besuPendingTransactions", params: [512]}
           |> request()
           |> json_rpc(json_rpc_named_arguments) do
```

**Comment by iampkuhz** [comment]
I found the reason.

The params only exist in `v6.3.0` to `v6.6.0`, while the recent `v6.7.0` to `v6.7.2` do not consist of this commit: 

https://github.com/blockscout/blockscout/blob/v6.7.0-beta/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/pending_transaction.ex

**Comment by iampkuhz** [comment]
@MASDXI thanks for your reply.

I'm using docker-compose to startup blockscout: https://github.com/blockscout/blockscout/tree/master/docker-compose

After double check on my docker compose, i found that docker image tag should be set in `service/backend.yml`. Otherwise, the latest version of docker compose would be installed.

After set version to 6.6.0, i could successfully query the pending transactions.

**Pull request merged**
