### PR TITLE
Fix empty TransferBatch event handling

### LINKED ISSUE #7908: NFT token transfers: "token_id" is "null" for an item
### Example

https://eth-goerli.blockscout.com/token/0xA0E1b46e99459e45B2AC1122Bc0594A585c481e2

for one of the item in the response of token transfers `token_id` field is set to `null` that should not be for `ERC-1155` tokens

```json
{
  "block_hash": "0x61b720e40f8c521edd77a52cabce556c18b18b198f78e361f310003386ff1f02",
  "from": {
    "hash": "0x598AF04C88122FA4D1e08C5da3244C39F10D4F14",
    "implementation_name": null,
    "is_contract": false,
    "is_verified": null,
    "name": null,
    "private_tags": [],
    "public_tags": [],
    "watchlist_names": []
  },
  "log_index": "6",
  "method": "0x759631c6",
  "timestamp": "2023-05-26T03:28:36.000000Z",
  "to": {
    "hash": "0x0000000000000000000000000000000000000000",
    "implementation_name": null,
    "is_contract": false,
    "is_verified": null,
    "name": null,
    "private_tags": [],
    "public_tags": [],
    "watchlist_names": []
  },
  "token": {
    "address": "0xA0E1b46e99459e45B2AC1122Bc0594A585c481e2",
    "circulating_market_cap": null,
    "decimals": null,
    "exchange_rate": null,
    "holders": "5519",
    "icon_url": null,
    "name": "Isekai Battle Weapons",
    "symbol": "WPN",
    "total_supply": null,
    "type": "ERC-1155"
  },
  "total": {
    "decimals": null,
    "token_id": null,
    "value": null
  },
  "tx_hash": "0xa6ad6588edb4abd8ca45f30d2f026ba20b68a3002a5870dbd30cc3752568483b",
  "type": "token_burning"
}

```

### PR DESCRIPTION
**Pull request by atapin**
Fixes #7908 

## Motivation

Due to https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4461, the indexer creates empty batch transfers. This fix skips empty batch transfers

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs

### CODE REVIEW

**Comment by atapin** [comment]
Note: after this PR, the database should be cleaned up from the token transfers with `token_ids=null`. As external contributor, I can't check if all such records are eligible for removal.

**Comment by nikitosing** [comment]
@atapin Hello, PR lgtm, but could you please create a migration which will delete all the token transfers with empty token_ids for erc-1155 tokens. Migration should looks like:
```
defmodule Explorer.Repo.Migrations.DeleteErc1155WithEmptyTokenIds do
  use Ecto.Migration

  def change do
    execute("""DELETE from token_transfers JOIN tokens on token_transfers.token_contract_address_hash = tokens.contract_address_hash WHERE tokens.type="ERC-1155" AND (token_transfers.token_ids = [] OR token_transfers.token_ids IS NULL) ;""")
  end
end

```
You can create migration via: `mix ecto.gen.migration delete_erc_1155_tt_with_empty_token_ids`

**Comment by atapin** [comment]
@nikitosing how to fix dropping DB connection in the CI pipeline?

**Comment by atapin** [comment]
@nikitosing could you check the tests? It seems the DB connection error is common for all PRs at the moment

**Comment by atapin** [comment]
@nikitosing just a reminder

**Review by nikitosing — APPROVED** [review]

**Comment by nikitosing** [comment]
@atapin Hello, please move your changelog entry from 4.2.1 release to `Current`

**Comment by atapin** [comment]
@nikitosing fixed

**Pull request merged**
