### PR TITLE
Add ENS support

### LINKED ISSUE #709: Add ENS support

### LINKED ISSUE #5572: Support ENS names
Support ENS names in EVM networks - show a corresponding ENS name for the address as public tag.  

Tags should be visible on the Address page, on Transaction page, in Account, etc.

### PR DESCRIPTION
**Pull request by mainnet-pat**
closes #709
closes #5572

## Motivation

This PR is a cherry picked and squashed set of changes required to enable ENS support which we have added for [smartBCH](https://smartbch.org) [network](https://helpme.cash). Our deployments are:
https://sonar.cash for smartBCH mainnet
https://testnet.sonar.cash for smartBCH Amber testnet
http://144.202.47.119:4000 for ethereum mainnet. This is a testbed for this PR and won't persist online for long, only indexes blocks 15000000 to 15001000

### Enhancements

* Add lookup for ENS address by name (forward lookup)
* Add lookup for ENS primary name by address (reverse lookup)
* Names are stored in `address_name` table with `primary=false`, `metadata={"type": "ens"}`
* Add ENS name fetcher task: names are fetched for all addresses in db upon indexer start, realtime indexer fetches all addresses in a block and fetches ENS names for them
* Add ENS Name sanitizer task: every hour all ENS names with addresses in db are checked if they still point to that address, otherwise purged from db.
* Add forward and backward ENS lookup rest api endpoints
* Add ENS support as an opt-in feature, `ENABLE_ENS` feature must be set to `true` **and** either `ENS_REGISTRY_ADDRESS ` or `ENS_RESOLVER_ADDRESS` env variables must be set. If your ENS deployment uses single public resolver, set `ENS_RESOLVER_ADDRESS` to spare a network call, otherwise resolver address will be queried from registry for every single name making two network calls for any lookup.
* Add capability to search by ENS names in the search field. When typing full name in the search field, also non-primary names and names with 0 transactions will be findable.
* Addresses with a registered ENS names will show their ENS name and ENS avatar on the `/address/` page. [vitalik.eth](http://144.202.47.119:4000/address/0x8B4Cf4139df80e0bF2Ea9A1C55552846C4fC24bd). Avatars are fetched from metadata server. `ENS_METADATA_SERVER` holds the relevant url endpoint. Example for eth mainnet: `https://metadata.ens.domains/mainnet`

### Incompatible Changes

No breaking changes

## Upgrading

ENS support is opt-in, reindexing is not required, names will be fetched upon server restart.

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [X] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Comment by vbaranov** [comment]
@mainnet-pat awesome, thank you! We will review. Meanwhile, could you address failing tests in CI?

**Comment by mainnet-pat** [comment]
thank you, I will see what I can do to fix the issues. I am not too familiar with elixir, this is my first time coding it.

**Comment by mainnet-pat** [comment]
Hey @vbaranov I am struggling with proper opt-in configuration for ens tasks. As of latest commit I have added check, not to push to indexer task if ens support was disabled. However, I somehow I still get:
```
     ** (exit) exited in: GenServer.call(Indexer.Fetcher.ENSName, {:buffer, [%Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 53>>}]}, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```
which indicates that the catchup indexer tries to push data to the ens worker. Am I missing some magic config option?

**Comment by mainnet-pat** [comment]
Also I do not quite get how to fix `gettext` checks

**Review by ponury1990 — APPROVED** [review]

**Pull request closed without merging**
