### PR TITLE
Get rid of downloading each NFT media for determining it's type (vide…

### LINKED ISSUE #5857: Blockscout throwing 500 when loading some tokens
There are some issues with possibly the current release of Blockscout (started seeing this on 08/08/2022).

The following ERC721s throw a **500** with no information:
https://blockscout.com/xdai/mainnet/token/0x5550f0d022f706d03ad25a72c477684d3416193f/instance/9665/token-transfers
https://blockscout.com/xdai/mainnet/token/0x2043f330339e21afe6dc6207500b24acf74068fc/instance/210/token-transfers

However, this is not applicable to all tokens, some like the following works:
https://blockscout.com/xdai/mainnet/token/0x22c1f6050e56d2876009903609a2cc3fef83b415/instance/5467516/token-transfers

Image of issue:

image

### PR DESCRIPTION
**Pull request by nikitosing**
…o or image)

Close #5857 

## Changelog
- now all NFT media loading as video with `poster` parameter as fallback 

If you need to turn on sound on video: 
- click with right mouse button on video
- select `Show all control elements` or `Show settings`
- turn on sound in player

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@nikitosing the issue is with Inventory tab. In the current implementation video will autoplay there. Imagine someone opens inventory full of videos with autoplay enabled. It looks like this is not good from performance perspective.

**Comment by nikitosing** [comment]
> @nikitosing the issue is with Inventory tab. In the current implementation video will autoplay there. Imagine someone opens inventory full of videos with autoplay enabled. It looks like this is not good from performance perspective.

@vbaranov 
in `get_media_src(metadata, high_quality_media?)` `high_quality_media?` parameter will not allow to display video on inventory tab

**Comment by vbaranov** [comment]
> in get_media_src(metadata, high_quality_media?) high_quality_media? parameter will not allow to display video on inventory tab

Meanwhile, video is autoplaying on inventory tab.

**Comment by vbaranov** [comment]
Closed in favour https://github.com/blockscout/blockscout/pull/6091

**Pull request closed without merging**
