### PR TITLE
At contract write support wei precision

### PR DESCRIPTION
**Pull request by theqp**
Using floating point numbers is not good for money. This is even more true if you are doing operations.

### Bug Fixes
When given 1.002001 as value it will be 1.002001, not 1.002000999999999872, also 0.000000000000000001 Eth will work.

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
Hi, thanks for PR! Didn't you forget to import `BigNumber`?

**Comment by theqp** [comment]
@vbaranov Indeed, I have fixed it. By the way I tested this but the reason for the missing import was that I done this on the v4.0.0-beta release and didn't test the merge.

**Review by vbaranov — APPROVED** [review]

**Comment by nikitosing** [comment]
@theqp I haven't watched yet, but could you please fix `ESLint` test, please?

**Comment by nikitosing** [comment]
you can run `./node_modules/.bin/eslint --format=junit --fix js/**` from `apps/block_scout_web`

**Comment by theqp** [comment]
@nikitosing done

**Review by nikitosing — APPROVED** [review]

**Comment by vbaranov** [comment]
@theqp thanks, finalized and merged https://github.com/blockscout/blockscout/pull/5047

**Pull request closed without merging**
