### PR TITLE
Fixed the `qemu: uncaught target signal 11 (Segmentation fault) - core dumped` when running `docker-compose up` on Apple Silicon

### PR DESCRIPTION
**Pull request by LucRyan**
No existing issue found.

## Motivation

There's an `qemu: uncaught target signal 11 (Segmentation fault) - core dumped`  error happens when running the docker locally on M1 MacBook Pro.
see similar issues in: https://github.com/docker/for-mac/issues/5123

### Bug Fixes
- [changed to update qemu-x86_64 for alpine to fix the signal 11 error.](https://github.com/blockscout/blockscout/commit/7b832bf8d14c02c3a264a2e92e208d614cfef860)

Before: stopped during initialization.
Screen Shot 2022-04-12 at 9 35 38 PM

After: it works!
Screen Shot 2022-04-12 at 10 12 51 PM

## Checklist for your Pull Request (PR)
  - [X] I added an entry to `CHANGELOG.md` with this PR
  - [X] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs

### CODE REVIEW

**Comment by vbaranov** [comment]
@LucRyan which version of Docker do you use on that machine?

**Comment by ryanwangJC** [comment]
Screen Shot 2022-04-13 at 12 34 02 PM

Hey @vbaranov I'm using 4.7.0 (77141) on MacBook Pro (16-inch, 2021) with Apple M1 Pro chip.

**Comment by vbaranov** [comment]
@ryanwangJC and what does `docker --version` return in terminal?

**Comment by ryanwangJC** [comment]
Docker version 20.10.14, build a224086

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
