### PR TITLE
API rate limiting

### PR DESCRIPTION
**Pull request by vbaranov**
## Motivation

The rate limiting for API in the application is not implemented.

## Changelog

Implement rate limit on all API endpoints through [Hammer](https://hex.pm/packages/hammer) Hex package with in-memory ETS as a backend.

`API_RATE_LIMIT` environment variable is introduced as the maximum requests per second with the default value 30 reqs/sec.

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Comment by bernatfp** [comment]
@vbaranov Hey, I'm getting rate limited way before hitting 30 requests per second.

For instance, just loading https://blockscout.com/xdai/mainnet/api?module=contract&action=getsourcecode&address=0x734c9A1F293c572002B088Fc7624c7d4F5D378ea on my browser and manually reloading a few times throws a `429`.

**Comment by vbaranov** [comment]
@bernatfp this is a global rate limit until we implement keys for API authorization.

**Comment by bernatfp** [comment]
@vbaranov got it! Sadly, this will likely block most teams from using Blockscout for any serious use case. When do you plan to implement API keys?

**Comment by yawhide** [comment]
we are one such team that rely on blockscout at cointracker.io to support ETC addresses but now can no longer support thousands of users.

someone could write a curl script that would bring the whole api down forever doing `while true: curl blockscout.com/...`. Could we instead do an IP based rate limit?

**Comment by vbaranov** [comment]
API authorization through the keys should be delivered in 1-2 months. The current global rate limit is configurable. If ETC DB instance has more capacity than withstand the current 30 reqs/sec, probably you could ask @diega to increase the rate limit on ETC instance until API keys functionality implementation. In order to set custom rate limit for API instance maintainer should set this environamnt variable:
```
export API_RATE_LIMIT = n # where n - number of requests per second.
```

**Comment by vbaranov** [comment]
> Could we instead do an IP based rate limit

@yawhide Technically, hex package which is used for rate-limiting, supports ip-based configuration, but most of the dapps do not have dedicated IP, so we didn't put much attention to this option. We will try to implement this option before API keys since it is demanded. And you'll need to ask the maintainer of the Blockscout instance to whitelist IP for your dapp.

**Comment by diega** [comment]
Hello @yawhide, feel free to reach me at diego <at> etccooperative <dot> org and we can see if our server is able to handle your load

**Comment by vbaranov** [comment]
@diega release 4.1.1 with support of allotted API rate limit based on IP is issued https://github.com/blockscout/blockscout/releases/tag/v4.1.1-beta. I applied it to all branches (ETC/Kotti/Mordor). Please update your instances. This release should also resolve this issue https://github.com/blockscout/blockscout/issues/4731. Please let me know once the instances will be updated - I will check if the issue is gone.

In regards, dedicated IP-based rate limit:
- the default value is 50 reqs/sec for every IP in the whitelist
- in order to change the default value, you should set `API_RATE_LIMIT_BY_IP` env variable
- the list of IPs is set through a comma-separated list in `API_RATE_LIMIT_WHITELISTED_IPS` env variable

**Comment by diega** [comment]
Hello @vbaranov.
I upgraded the branch for Kotti, then I removed the `blockscout_prod_classic` image and proceed with the `make start` and now the image is not building.
This is the command I ran with its output
```
$ ETHEREUM_JSONRPC_VARIANT='geth' ETHEREUM_JSONRPC_WS_URL='ws://127.0.0.1:8546' ETHEREUM_JSONRPC_HTTP_URL='http://127.0.0.1:8545' ETHEREUM_JSONRPC_TRACE_URL='http://127.0.0.1:8545' MIX_ENV='prod' DATABASE_URL='*********' SOCKET_ROOT='/etc/kotti' PORT='4000' SUPPORTED_CHAINS='[ { "title": "Ethereum Classic", "url": "https://blockscout.com/etc/mainnet"}, { "title": "ETC Mordor", "url": "https://blockscout.com/etc/mordor", "test_net?": true }, { "title": "POA Core", "url": "https://blockscout.com/poa/core" }, { "title": "POA Sokol", "url": "https://blockscout.com/poa/sokol", "test_net?": true }, { "title": "xDai Chain", "url": "https://blockscout.com/poa/dai" }, { "title": "Kovan Testnet", "url": "https://blockscout.com/eth/kovan", "test_net?": true }, { "title": "RSK Mainnet", "url": "https://blockscout.com/rsk/mainnet", "other?": true }, { "title": "LUKSO L14 testnet", "url": "https://blockscout.com/lukso/l14", "test_net?": true }, { "title": "Ethereum Mainnet", "url": "https://blockscout.com/eth/mainnet" }]' TXS_COUNT_CACHE_PERIOD='7200' BLOCKSCOUT_HOST='blockscout.com' NETWORK_PATH='/etc/kotti' API_PATH='/etc/kotti' SUBNETWORK='Kotti' CHAIN_ID='6' BLOCK_COUNT_CACHE_PERIOD='7200' LINK_TO_OTHER_EXPLORERS='true' LOGO='/images/classic_ethereum_logo.svg' LOGO_FOOTER='/images/classic_ethereum_logo.svg' NETWORK_ICON='_test_network_icon.html' COIN='ETC' NETWORK='ETC' POOL_SIZE='100' POOL_SIZE_API='50' CHAIN_SPEC_PATH='https://raw.githubusercontent.com/etclabscore/core-geth/master/params/parity.json.d/kotti.json' BLOCKSCOUT_VERSION='v4.1.1-beta' PORT=80 make start
make[1]: Entering directory '/home/ubuntu/blockscout/docker'
==> Checking for blockscout image blockscout_prod_classic
==> No image found trying to build one...
Sending build context to Docker daemon  14.01MB
Step 1/25 : FROM bitwalker/alpine-elixir-phoenix:1.12
# Executing 1 build trigger
 ---> Using cache
 ---> 88b4cd1ca081
Step 2/25 : RUN apk --no-cache --update add alpine-sdk gmp-dev automake libtool inotify-tools autoconf python3 file
 ---> Using cache
 ---> 87cc38eb921d
Step 3/25 : RUN set -ex &&     apk --update add libstdc++ curl ca-certificates &&     for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION};         do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add --allow-untrusted /tmp/*.apk &&     rm -v /tmp/*.apk &&     /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib
 ---> Running in 57e9db3c9d6d
+ apk --update add libstdc++ curl ca-certificates
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
OK: 359 MiB in 84 packages
+ curl -sSL /releases/download//glibc-.apk -o /tmp/glibc-.apk
curl: (3) URL using bad/illegal format or missing URL
+ curl -sSL /releases/download//glibc-bin-.apk -o /tmp/glibc-bin-.apk
curl: (3) URL using bad/illegal format or missing URL
The command '/bin/sh -c set -ex &&     apk --update add libstdc++ curl ca-certificates &&     for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION};         do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done &&     apk add --allow-untrusted /tmp/*.apk &&     rm -v /tmp/*.apk &&     /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib' returned a non-zero code: 3
make[1]: *** [Makefile:454: build] Error 3
make[1]: Leaving directory '/home/ubuntu/blockscout/docker'
make: *** [Makefile:471: start] Error 2
```
do you want me to open another issue?

**Comment by vbaranov** [comment]
Hi @diega unlikely this is an issue with Dockerfile. This is rather a temporary issue of the unreachability of some of the URL. I would start the process again.

**Comment by diega** [comment]
@vbaranov thanks for taking a look at it.
It seems to me that the image is not being able to resolve the `GLIBC_VERSION` nor the `GLIBC_REPO` environment variables. I don't know if that something that should be exposed by the base image

**Comment by vbaranov** [comment]
@diega indeed, you're right. I fixed the Kotti branch. Just pushed the update.

**Comment by vbaranov** [comment]
I fixed Mordor branch as well. Classic mainnet branch looks ok.

**Comment by diega** [comment]
Thanks a lot @vbaranov. I just upgraded every instance and everything looks fine

**Comment by vbaranov** [comment]
Great, thank you. Now you can configure a dedicated API rate limit on your users' demand. The issue https://github.com/blockscout/blockscout/issues/4731 resolved as well.

**Pull request merged**
