### PR TITLE
API v2: new methods

### PR DESCRIPTION
**Pull request by nikitosing**
## Changelog
- Add `/search/check-redirect`
- Add `type` query parameter to `/tokens` in order to filter by token type
- Add `/addresses/{address_hash}/token-transfers?token={token_address_hash}`
- Add `method`, `block_hash` and `log_index` fields to token transfers
- Add `tx_hash` field to logs
- Add `coin_balance` to address in `/addresses`

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@nikitosing 

get `api/v2/search/check-redirect` responds with

```
Phoenix.ActionClauseError at GET /api/v2/search/check-redirect
no function clause matching in BlockScoutWeb.API.V2.SearchController.check_redirect/2
The following arguments were given to BlockScoutWeb.API.V2.SearchController.check_redirect/2:

    # 1
    %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %{}, cookies: %
...
```


Is this expected?

**Comment by nikitosing** [comment]
@vbaranov Yes, in such a case back-end sends 400 response, this is expected

**Comment by vbaranov** [comment]
> @vbaranov Yes, in such a case back-end sends 400 response, this is expected

Which type of call will be successful?

**Comment by nikitosing** [comment]
@vbaranov `/api/v2/search/check-redirect?q=0x0`

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
