### PR TITLE
add missing keys

### PR DESCRIPTION
**Pull request by cen1**
## Motivation

Bugfix

### Bug Fixes

We noticed exceptions being thrown in indexer because of these two missing keys on sgb/ava node. Adding these two to the list fixed the exceptions.

Unfortunately I am way out of my depth when it comes to elixir to write any tests or even know what this code does so please review or prepare your own fix if needed.

### CODE REVIEW

**Comment by vbaranov** [comment]
@cen1 thanks for the PR. Can you elaborate on exact version and link to the client, which is used for archive node?

**Comment by vbaranov** [comment]
@cen1 thanks for the PR. Can you elaborate on exact version and link to the client, which is used for archive node?

**Comment by vbaranov** [comment]
@cen1  Closed in favour https://github.com/blockscout/blockscout/pull/5301. Still curious about client version and refernce to the client.

**Comment by cen1** [comment]
https://github.com/flare-foundation/flare/tree/v0.5.3

**Pull request closed without merging**
