### PR TITLE
Add /block route with temp redirect patch

### LINKED ISSUE #4455: Support EIP3091
[EIP3091](https://eips.ethereum.org/EIPS/eip-3091) describes a standard for API Routes for Blockchain explorers. 

Routes that don't follow the standard are, according to [this post](https://ethereum-magicians.org/t/eip-3091-block-explorer-api-routes/4907): 
- `/blocks` instead of `/block` 
- `/tokens` instead of `/token`

A simple 301 redirect could probably solve this issue, quite painful for dApps that support many networks.

### Environment

N/A

### Steps to reproduce
Go to https://explorer.fuse.io/block/12218333

### Expected behaviour
https://explorer.fuse.io/block/12218333 should show the block or redirect to https://explorer.fuse.io/blocks/12218333

### Actual behaviour
Returns a 404

### PR DESCRIPTION
**Pull request by pavancse17**
## Motivation

-  There is drafted EIP3091 going on to standardize /block, /token, /tx, /address routes.
-  Since it is not approved yet, I have added temp /block patch to satisfy any clients who are using `/block` route instead of `/blocks`.
-  We need to revisit once the EIP3091 got approved and do proper fix.

## Changelog

-  New get route `/block` which redirects to existing `/blocks`.

### Bug Fixes

#4455  

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by vbaranov — CHANGES_REQUESTED** [review]
@pavancse17 it looks like you used an old version of NPM, older than NPM 7. There is no need to change package-lock.json in both `block_scout_web` and `explorer` applications. Could you please remove those changes from the PR?

**Comment by pavancse17** [comment]
> @pavancse17 it looks like you used an old version of NPM, older than NPM 7. There is no need to change package-lock.json in both `block_scout_web` and `explorer` applications. Could you please remove those changes from the PR?

@vbaranov I undid those changes in 67ae14ff7cb01c0fb3bc155239a3802f8a69189d

**Comment by pavancse17** [comment]
Sorry I mistakenly closed the pull request :(

**Review by vbaranov — CHANGES_REQUESTED** [review]
The changes from PR didn't work for me as expected (see attached screenshots)

Screenshot 2021-08-30 at 15 56 37

Screenshot 2021-08-30 at 15 56 03

Also, PR doesn't cover supporting an extra path for a token which is suggested by EIP-3091.

**Comment by vbaranov** [comment]
@pavancse17 would you continue to work on this PR?

**Comment by pavancse17** [comment]
> @pavancse17 would you continue to work on this PR?

@vbaranov I didn't get time this week. I will try to fix this weekend.

**Comment by pavancse17** [comment]
@vbaranov  I have pushed the code that I have in my local. I won't be able to complete it fully at this time.

**Comment by vbaranov** [comment]
Closed in favor #4655

**Pull request closed without merging**
