### PR TITLE
Syscoin + Docker + Base fee parsing

### PR DESCRIPTION
**Pull request by sidhujag**
## Motivation

Add Syscoin resources (images)
Docker file to support builds from multi-stage docker environments like Puppeth
Add london hard fork support for parsing blocks from rpc

### CODE REVIEW

**Comment by sidhujag** [comment]
Here is the puppeth docker for context: https://github.com/sidhujag/go-ethereum/blob/nevm/cmd/puppeth/module_explorer.go#L32

**Review by vbaranov — COMMENTED** [review]
Thank you for bringing this up. I have several questions and suggestions.
- I would suggest splitting Docker config and base fee parsing into separate PRs since they are not related to each other.
- Could you please `squash` commits into one for each PR?
- What is the rationale to have Syscoin in the PR title?
- We keep Docker assets in the `docker` folder. Could you elaborate what is the rationale to keep Dockerfile in the  root folder?
- I guess sys_logo.svg is specific for Syscoin. I would suggest keeping it in your fork then.
- This Dockerfile is Geth specific. However, Blockscout supports multiple clients. Probably, we should keep this Dockerfile in `docker/geth folder`? What do you think?

**Comment by sidhujag** [comment]
> Thank you for bringing this up. I have several questions and suggestions.
> 
> * I would suggest splitting Docker config and base fee parsing into separate PRs since they are not related to each other.
> * Could you please `squash` commits into one for each PR?
> * What is the rationale to have Syscoin in the PR title?
> * We keep Docker assets in the `docker` folder. Could you elaborate what is the rationale to keep Dockerfile in the  root folder?
> * I guess sys_logo.svg is specific for Syscoin. I would suggest keeping it in your fork then.
> * This Dockerfile is Geth specific. However, Blockscout supports multiple clients. Probably, we should keep this Dockerfile in `docker/geth folder`? What do you think?

Agreed,

My goal was to not fork blockscout because it is so active, actually I plan to put resources if you allow to help build it to index more data to serve more use-cases like etherscan. I wanted to push the logo to official blockscout so we don't have to manage our own fork. (much like the other chains supported here https://github.com/blockscout/blockscout/tree/master/apps/block_scout_web/assets/static/images) I opened this up as a discussion and would intending to break them down into separate after discussion with you guys.

I think docker/geth or puppeth makes alot of sense, would you deploy it as blockscout/blockscout-geth (or puppeth) on docker hub?

**Comment by sidhujag** [comment]
I have created #4486, #4485, #4484 in response to comments and we can continue conversations there

**Pull request closed without merging**
