### PR TITLE
Update error pages

### LINKED ISSUE #6350: Update Error pages
Error to update: 
- 404
- 503 
- 422 Example: https://blockscout.com/eth/mainnet/address/0x6d2e03b7EfFEae98BD302A9F836D0d6Ab000276

### PR DESCRIPTION
**Pull request by sl1depengwyn**
Resolves #6350

## Changelog

- Updated old style errors (404, 422, tx not found)
- Return general 422 error page instead of invalid tx hash page
- Add static 503 page to configure it for return when application is not available

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

### CODE REVIEW

**Review by nikitosing — COMMENTED** [review]
Let's leave this error page without changes. Now it changed since you modified css. (title text size, shape of button)

image

**Review by nikitosing — COMMENTED** [review]
I think it's better to center error message vertically

image

**Review by vbaranov — CHANGES_REQUESTED** [review]
Screenshot 2022-12-08 at 17 39 30

**Comment by sl1depengwyn** [comment]
> Screenshot 2022-12-08 at 17 39 30

Fixed, thanks!

**Pull request merged**
