### PR TITLE
chore: Return old response format in /api/v1/health endpoint

### PR DESCRIPTION
**Pull request by vbaranov**
Resolves https://github.com/blockscout/blockscout/pull/11139#discussion_r1891627643

## Motivation

Return the old response format in `/api/v1/health` endpoint.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [x] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [x] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/setup/env-variables/README.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/setup/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/setup/env-variables).
- [x] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [x] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

## Summary by CodeRabbit

- **New Features**
	- Introduced a legacy health check endpoint to support older systems.
	- Added functionality to format responses for health check results and errors.

- **Bug Fixes**
	- Updated health check routing for backward compatibility, ensuring existing clients can still access the service.

- **Chores**
	- Enhanced routing structure to maintain compatibility with legacy API paths.

### CODE REVIEW

**Review by sl1depengwyn — APPROVED** [review]

**Comment by Elgayar777** [comment]
- [ ]

**Comment by Elgayar777** [comment]
- [ ]

**Review by Elgayar777 — COMMENTED** [review]
- [ ]

**Review by baxitfund — COMMENTED** [review]
Approved

**Pull request merged**
