### PR TITLE
fix block error

### PR DESCRIPTION
**Pull request by zjb0807**
Deduplication in database operations.

### CODE REVIEW

**Comment by vbaranov** [comment]
@zjb0807 could you please specify which exact error do you face?

**Comment by zjb0807** [comment]
```
2022-03-16T19:48:50.496 application=indexer fetcher=block_catchup first_block_number=128241 last_block_number=128232 [error] ** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time

    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:663: Ecto.Adapters.SQL.insert_all/9
    (ecto 3.7.1) lib/ecto/repo/schema.ex:58: Ecto.Repo.Schema.do_insert_all/7
    (explorer 0.0.1) lib/explorer/repo.ex:61: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:302: Explorer.Chain.Import.insert_changes_list/3
    (explorer 0.0.1) lib/explorer/chain/import/runner/address/coin_balances.ex:81: Explorer.Chain.Import.Runner.Address.CoinBalances.insert/3
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:1013: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
    (ecto 3.7.1) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
    (stdlib 3.16.1) timer.erl:197: :timer.tc/3
    (explorer 0.0.1) lib/explorer/repo.ex:37: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer 0.0.1) lib/explorer/chain/import.ex:333: anonymous fn/3 in Explorer.Chain.Import.import_transactions/
    (elixir 1.13.3) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.3) lib/enum.ex:2442: Enum.reduce_while/3
    (explorer 0.0.1) lib/explorer/chain/import.ex:332: Explorer.Chain.Import.import_transactions/2


Retrying.
```

**Comment by zjb0807** [comment]
image

It is recommended to use `Squash and merge` to merge code. This has only one commit on the master, which is convenient for tracking changes.

**Comment by vbaranov** [comment]
Closed in favour https://github.com/blockscout/blockscout/pull/5420

**Pull request closed without merging**
