### PR TITLE
[4274] Fix/improve search token-autocomplete

### PR DESCRIPTION
**Pull request by vsyrovat**
*Fix fall on search token-autocomplete by non-latin characters*
*Fix search token-autocomplete by multiple words"

This PR fixes https://github.com/blockscout/blockscout/issues/4274

No breaking changes IMHO

I don't know exactly is it possible to tokens be in non-latin characters. @vbaranov please check this point
This PR not fix search by, for example, "лучшие токены" - this search string will be treat as empty string.

  - [X] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@vsyrovat changes look good to me. 

`mix credo` suggests refactoring opportunities:
```
  Refactoring opportunities
┃
┃ [F] ↗ `with` contains only one <- clause and an `else`
┃       branch, use a `case` instead
┃       apps/explorer/lib/explorer/chain.ex:1129 #(Explorer.Chain.search_contract)
┃ [F] ↗ `with` contains only one <- clause and an `else`
┃       branch, use a `case` instead
┃       apps/explorer/lib/explorer/chain.ex:1103 #(Explorer.Chain.search_token)
```

**Comment by vsyrovat** [comment]
@vbaranov credo notes fixed

**Review by vbaranov — COMMENTED** [review]
@vsyrovat could you please also add an entry to CHANGELOG.md to the top of `### Fixes` section?

**Comment by vsyrovat** [comment]
> @vsyrovat could you please also add an entry to CHANGELOG.md to the top of `### Fixes` section?

Done a74d87615015dc128acccf102b4e7c40f3a9c60a

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
